### ISSUE TITLE
12th Man – Fair Football Ticket Market

### ISSUE THREAD

**Issue by sanpaulo** [Aventus-Network-Services/aventus-dapp-proposals#12]
Ether address: 0xBB3f735E7aD69EF9f635CAE882cB014E9bB60114
# 12th Man – Fair Football Ticket Market

![homeandlogin](https://user-images.githubusercontent.com/27300314/29994548-41c8056e-8fd2-11e7-9073-f5b643f5cabb.jpg)

## Problems:
As a number one sport in many countries, football has millions of fans. As a results the football ticket trade is a billion dollar market where thousands of tickets are traded all over the world every day. The experience of seeing a match live in the stadium is the best sensation, as every football fan knows. However, most fans do not see their favorite team that often due to many problems in the football ticket market. There are five main problems in the football ticket market that every football fan will recognize:

**Problem 1. Second hand ticket market is flooded by frauds:** Major sport events have the number one market where second hand ticket frauds are active [1]. Fans will transfer hundreds of dollars to someone they do not know and find out after several days that they will never receive their tickets. Though people know these scams exist, they put too much trust in total strangers. In 2015 in the UK alone there was a 5.2 million pound loss due to these scams [2].	

**Problem 2. Not all tickets are sold:** Many stadiums have more than 50.000 seats, but many seats remain empty. For matches that are not so popular the main reason will be that not all tickets are sold. This can be due to a lack of promotion, but also due to expensive ticket prices (problem 5) and a lack of a trustable platform where users can buy tickets. The Spanish football organization even wants to punish clubs who only partially fill there stadium [3].

**Problem 3: Business partners don’t always use their ticket:** Many companies buy tickets as gift for associates or partners. For example at the Dutch football cup final, 7% of the tickets was reserved for amongst others partners of the Dutch football organization and 3% for partners of the stadium [4]. It is not unthinkable that gifted tickets are less likely to be used, as the receivers did not pay money for it. However, to resell them could be too much trouble. 	

**Problem 4: Season card holders do not go to all matches and leave their seat empty:** Many seats for football matches are reserved for season card holders. For example, Arsenal has 61% of their seats reserved for card holders [5]. The most people will of course attend their match, but there are scenarios where one has to cancel (holiday, work, birthday, illness etc.). This leads to leaving their seat empty, while others would have wanted to go.	

**Problem 5. Tickets are too expensive:** Prices for football tickets can be very high. Though the average price of the cheapest match day Premier League ticket is around £30.68, it can be up to £50 for a cheapest Chelsea match ticket [6]. Football fans have been complaining about this the last years. A recent example is about Liverpool fans that walked out during the match to demonstrate against high tickets [7]. This excludes fans with limited financial means to go to matches. But also second hand tickets can be extraordinary expensive, as resellers are free to ask any price they like [8].

## Solutions:
The 12th Man DApp will contribute to the solution of the five main problems above in the following ways:

**Solution 1. Second hand ticket market is flooded by frauds:** Second hand tickets are sold on social media and other sites between complete strangers. With the Aventus protocol it is possible to stop this. Each ticket belongs to a certain person. When resold through the 12th Man app, the ticket will receive the name of the new person in the blockchain. This name can be checked for validity in the application and the blockchain itself. Frauds can no longer sell the same ticket to multiple persons and will cease to exist in the app. 

On top of that, sellers will have a registered account. This shows the name of the seller, some information, a profile picture, the number of sold tickets and his average rating. It could for example say, as shown in the mockup: “John Doe, 24 years. Has been a member of 12th Man since 2014. He sold 12 tickets and has been rated a 4.5/5.0 on average”. Both buyers as sellers will gain trust after each transaction and rating.

![matchandseller](https://user-images.githubusercontent.com/27300314/29994558-8879a544-8fd2-11e7-8f20-806516ec2efe.jpg)

Note that reselling will be disabled if it is not compliant to national laws. For example reselling is not allowed in England [9], but is allowed in Spain [10]. The 12th Man DApp however strives to receive the status as official reseller in countries where it is necessary.

**Solution 2. Not all tickets are sold:** As said before, sellers of match tickets (e.g. Premier League clubs) often have trouble selling all tickets. They can use several strategies for matches that are not popular with the Aventus Protocol. There are endless possibilities, but some examples are:	
1. Dynamic pricing: offer discount (3 days before -10%, 2 days before -20%, 1 day before -25%)
2. Trigger possibility for promoters to sell for all unpopular matches and give them a fee	
3. Trigger possibility for promoters to sell if 50% is not sold before a certain date and give them a fee
4. Offer discount if someone re-tweets or shares the event on Facebook (spread the word)
5. Offer small cashback if someone stimulates another to buy a ticket (e.g. through affiliate links)

**Solution 3: Business partners don’t always use their ticket:** When gifted tickets are not used, other fans have to be disappointed. Even popular matches often have some seats empty. When an organization gives away tickets they can choose the “redeem before a certain date”-option. This means that the recipient can redeem the ticket in the DApp before a certain date (for example until 5 days before the match), whereafter the link becomes invalid and the ticket will be sold through the application again. This also will satisfy the Club, as their stadium is more filled.

**Solution 4: Season card holders do not go to all matches and leave their seat empty:** A new service is lending the card of season card holders. When the owner is unable to go, they can lend the ticket for a fee (e.g. 80% of the regular ticket price) to another fan. There are two possible methods for doing this, which will be dependent on the clubs cooperation. Option 1 is that a temporary ticket is produced with the name and identity of the buyer in the blockchain. That will be the desirable option as it is the easiest and most reliable. Option 2 is the physical lending of the season card between the buyer and seller for this particular match’ ticket. This will need some guarantees, such as a verified identity and home address of the buyer and a deposit, which will be refund if the season card gets returned.	 

**Solution 5. Tickets are too expensive:** Second hand sellers often sell tickets for far too high prices. Through the DApp the official resellers can put a limit on the prices of second hand tickets. They will often allow the seller to get some profit, but not to gain hundreds of dollars per ticket. This will make the second hand market a fair level playing field for all parties: fans can access fair priced tickets, while second hand sellers still can make some profit.

## How it works:
The 12th Man DApp will fight the five main problems and create a fair football ticket market for both the primary market as the secondary market. In that way the traditional sellers will sell tickets through the DApp, second hand resellers have a chance to resell (while not asking too high prices) and the real football fans have more opportunities to get a match ticket for a fair price.

Event creators (the football clubs) can open ticket sales through the 12th Man DApp with the Aventus protocol underlying. This will be the primary market and will be fully customizable. They can choose to sell tickets just as they do now (stable price) for popular matches. The underlying Ethereum blockchain keeps record of which ticket belongs to which identity [11]. However, they have many other options as well, which have been described above: dynamic prices, redeem before a certain date, allow resell, allow season card lending and allow affiliate promotion.

Ticket buyers will have their identity coupled to the tickets they buy. When they are not able to attend the match, they can resell their ticket through the DApp. The event creator might have put a limit on the price of the ticket, but will probably still get a reasonable fee. The original ticket buyer puts up his ticket for sale and is now a seller.

A new ticket buyer search the DApp for tickets and selects the ticket that the ticket seller has put up. He can select his account to see if he looks reliable. When he decides to buy the ticket he has different payment options: pay with crypto currencies (through AVT/fiat or ETH/fiat conversion) or more conventional methods like credit card or bank transfer. After confirmation the name of the new buyer will be coupled to the ticket in the blockchain and the old ticket is no longer useable.

When promoters are allowed they will have affiliate links which refers buyers to the 12th Man DApp through their personal link. When a buyer successfully buys a ticket they will get a fee as reward.

## Why football only?
Football fans feel very connected and have developed their own culture in many clubs and regions. For some, football is the most important event of the week. Supporters of the same club will immediately sympathize with each other. No wonder that the supporters of a club are often referred to as the 12th man. But also many friends who supporter different clubs watch together. As a result football fans will have more trust and faith in a football oriented community: From Fans, for fans.

## Added value for Aventus Ecosystem:
The key players and systems in the Aventus Ecosystem are: the Event Creators, Promoters, Ticket Buyers, DApps like the 12th Man, The Aventus Protocol and the Ethereum Blockchain. To illustrate the dynamics of this Ecosystem an example is illustrated below. In the example Manchester United is playing a match against Bayern München and wants to sell tickets through the 12th Man. They allow promotion (Promoter Evan Green) and reselling. George Bell serves as example buyer.

![aventusecosystem](https://user-images.githubusercontent.com/27300314/29994591-416e96f4-8fd3-11e7-9cbf-24273d6e263f.jpg)

The primary and secondary market for football tickets is a billion dollar market with millions of buyers and sellers, but still have many problems as described above. The DApp will be one of the most used applications based on the Aventus Protocol and will inspire other developers to develop their own use case.

## Regular monetisation:
The main source of revenues is through a fixed percentage on every sold ticket. The revenues are divided differently for every other ticket sort and organiser. But some examples could be:

**Primary market ticket**
-	2% fee for 12th Man (this fee will be fixed to guarantee revenues)
-	98% revenue for the Club

**Second hand ticket:**
-	2% fee for 12th Man
-	8% fee for the Club
-	90% revenue for the second hand seller

**Season card loan:**
-	2% fee for 12th Man
-	10% fee for the Club
-	88% revenue for the season card lender

**Promotional sale:**
-	2% fee for 12th Man
-	86% fee for the Club
-	12% revenue for the promoter

## Monetisation through optional targeted advertising:
Advertisement is also a multi-billion dollar market. Besides, the 12th Man is a perfect platform for targeted advertising as all costumers will be into football and the lead generation percentage will be high. The behavior of users can be tracked and advertisements can be customized to fit every individual. 

However, no one likes to receive ads on each site they visit and especially not on the limited space of a mobile phone. The 12th Man offers a solution that can satisfy everyone. Users can choose if they want to enable advertisements and sending their site behavior (anonymously) to advertisers. If they disable this option they will receive NO ads and their data will NOT be shared with advertisers.

If they do choose to enable advertisements they will get (financial) rewards. Normally users never get paid for viewing advertisements. The revenues are paid from the advertisers to the publisher. This is a reason why adblockers are getting increasingly popular. A new method to stimulate users to enable advertisements is providing them with a share of the revenues, like Basic Attention Token does in their new browser [12]. In the 12th Man DApp users will get 50% of the revenues of advertisements and are thus rewarded for using the app.

## Distribution of revenues:
The revenues that are gathered through the 2% fee per ticket and targeted advertisements will be distributed in the following way:

**Development (30%):** The most demanding point at the moment is the development of the application. Because the 12th Man is just a concept and not an existing product, there has to be investments in the development of the application. This will be available through regular browsers (Chrome, Internet Explorer, Firefox etc.) and popular mobile-based app stores (AppStore, Android etc.). The development will start with 30% of the revenues. After the product launch the revenue distribution for development will decrease to 15% to secure future updates and additions. The remaining 15% will go to advertisement and promotion.

**Advertisement and promotion (25%):** Another important point in the first months is adding value to the 12th Man platform. This means getting official sellers to use the platform, promoters to sell tickets and users to buy and resell tickets. The first part will be an issue of talking to football clubs and explaining the win-win situation for every party. The second part is getting users to the platform. This will be mainly done through advertisements and promotional actions where people can win prizes by for example sharing Twitter and Facebook posts about the application.

**Maintenance and support (15%):** Customer satisfaction and support will be key in the application. That is why 15% is reserved for maintaining the applications, having the servers up and running and finding bugs. Besides, support will be available for customers through email, phone and social media.

**Legal (10%):** Ticket reselling is illegal in certain countries and needs to be carefully examined. A legal advisor will make sure that the application is compliant to relevant laws. Remaining revenues from this will be saved in a buffer for any possible legal cases.

**Team income (20%):** The remaining part will be used to pay the 12th Man team.

## Planning:
**Q4 2017**
Public Beta Aventus
Start development 12th Man applications

**Q1 2018**
Testing 12th Man Applications
Promotion amongst official tickets sellers

**Q2 2018**
Aventus Production Launch
12th Man Production Launch
Promotion amongst official tickets sellers and users

**Q3 2018**
Promotion amongst official tickets sellers and promoters
Promotional actions with prizes to get more users

**Q4 2018**
Evaluate process so far
Plan for 2019

## References
[1] “Social media users warned over rise in online ticket fraud”
https://www.theguardian.com/money/2016/mar/21/online-ticket-fraud-social-media-users-warned-twitter-facebook-get-safe-online
[2] “Ticket fraud: Social media sites 'must do more to tackle issue'”
http://www.bbc.com/news/uk-36348757
[3] “La Liga season preview: Empty seats to be punished”
https://www.irishtimes.com/sport/soccer/la-liga-season-preview-empty-seats-to-be-punished-1.2762324 
[4] “KNVB Bekerfinale: Tickets to the final”
http://www.knvb.nl/nieuws/betaald-voetbal/knvb-beker/24414/knvb-bekerfinale-tickets-final 
[5] “Highest percentage of season ticket holders at Premier League clubs”
http://www.express.co.uk/pictures/pics/4737/Highest-percentage-season-ticket-holders-Premier-League-sportgalleries 
[6] “Ticket prices: How much does it cost to watch your team?”
http://www.independent.co.uk/sport/football/premier-league/ticket-prices-how-much-does-it-cost-to-watch-your-team-a6694486.html 
[7] “Liverpool ticket prices: Thousands of fans walk out in protest”
http://www.bbc.com/sport/football/35513425 
[8] “Independent Review of Consumer Protection Measures concerning Online Secondary Ticketing Facilities”
http://www2.warwick.ac.uk/fac/soc/economics/staff/mjwaterson/ind-16-7-independent-review-online-secondary-ticketing-facilities.pdf 
[9] “Ticket Touting, Ticket Fraud and the Law”
https://www.unlockthelaw.co.uk/News/Ticket-touting-ticket-fraud-and-the-law.html 
[10] “Can I lend the membership card to somebody else?”
https://suport.fcbarcelona.com/hc/en-us/articles/211873269-Can-I-lend-the-membership-card-to-somebody-else-
[11] “Aventus Whitepaper”
https://aventus.io/doc/whitepaper.pdf

**Comment by annikamonari** [comment]
This proposal has been approved.

**Comment by LegalEngineering** [comment]
Congrats!
